# Generates a (p, q) torus knot tube as an OBJ with smooth normals.
# Usage: torusknot.py out.obj [segments] [sides]
import math, sys

out = sys.argv[1]
segments = int(sys.argv[2]) if len(sys.argv) > 2 else 192
sides = int(sys.argv[3]) if len(sys.argv) > 3 else 16
p, q = 2, 3
tube = 0.14

def curve(t):
    r = 0.6 + 0.25 * math.cos(q * t)
    return (r * math.cos(p * t), 0.25 * math.sin(q * t), r * math.sin(p * t))

def sub(a, b): return (a[0]-b[0], a[1]-b[1], a[2]-b[2])
def add(a, b): return (a[0]+b[0], a[1]+b[1], a[2]+b[2])
def mul(a, s): return (a[0]*s, a[1]*s, a[2]*s)
def cross(a, b): return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])
def norm(a):
    l = math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2])
    return (a[0]/l, a[1]/l, a[2]/l)

positions, normals = [], []
for i in range(segments):
    t = 2 * math.pi * i / segments
    c = curve(t)
    tangent = norm(sub(curve(t + 1e-3), curve(t - 1e-3)))
    # A frame around the tangent; (0,1,0) is never parallel to this knot's tangent
    binormal = norm(cross(tangent, (0, 1, 0)))
    normal = cross(binormal, tangent)
    for j in range(sides):
        a = 2 * math.pi * j / sides
        n = add(mul(normal, math.cos(a)), mul(binormal, math.sin(a)))
        positions.append(add(c, mul(n, tube)))
        normals.append(n)

with open(out, 'w', newline='\n') as f:
    f.write(f'# ({p},{q}) torus knot, {segments}x{sides}, generated by torusknot.py\n')
    for v in positions:
        f.write('v %.5f %.5f %.5f\n' % v)
    for n in normals:
        f.write('vn %.4f %.4f %.4f\n' % n)
    for i in range(segments):
        for j in range(sides):
            a = i * sides + j + 1
            b = ((i + 1) % segments) * sides + j + 1
            c = ((i + 1) % segments) * sides + (j + 1) % sides + 1
            d = i * sides + (j + 1) % sides + 1
            f.write(f'f {a}//{a} {b}//{b} {c}//{c} {d}//{d}\n')
print(f'{out}: {len(positions)} vertices, {segments * sides * 2} triangles')
